### PR TITLE
Update action internals and bump major

### PR DESCRIPTION
**Pull request by rathpc**
This includes:
- Updating dependencies to latest
- Update package-lock.json to latest version
- Resolve lint issues as a result of updating deps
- Update action to run using node16
- Bump version to 2.0.0

### CODE REVIEW

**Comment by rathpc** [comment]
@dcoraboeuf when you have a chance this updates the action to use newer deps etc.

**Comment by dcoraboeuf** [comment]
There seems to be an issue with the build, I'll check tomorrow morning my time since I am on my mobile phone and this is not so practical to check things...

Thanks already for your contribution!

**Comment by rathpc** [comment]
> There seems to be an issue with the build, I'll check tomorrow morning my time since I am on my mobile phone and this is not so practical to check things...
> 
> Thanks already for your contribution!

Ontrack cli setup step has an issue here https://github.com/nemerosa/ontrack-github-actions-cli-validation/pull/1/checks#step:4:9 and as a result does not output a branch to use in subsequent steps. There may be other issues but I would start there.

**Comment by dcoraboeuf** [comment]
I've fixed the support for PRs in the `setup` action and updated the CLI version in the `main` branch. I've also created a `v2.0.1` for this purpose.

Can you rebase or merge your PR head branch from the `main` branch?

**Comment by rathpc** [comment]
> I've fixed the support for PRs in the `setup` action and updated the CLI version in the `main` branch. I've also created a `v2.0.1` for this purpose.
> 
> Can you rebase or merge your PR head branch from the `main` branch?

Updated just now

**Comment by rathpc** [comment]
@dcoraboeuf just bumping this up. I also left a comment on the other action PR regarding versions in case you had missed it.

**Comment by dcoraboeuf** [comment]
Version issue is now fixed.

**Comment by dcoraboeuf** [comment]
The build now fails with:

> Error: No current configuration

Having a look.

**Comment by dcoraboeuf** [comment]
After some back and forths, it all comes down to the fact that secrets are not passed for PR coming for forks: https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow

> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

I therefore need to disable all the `ontrack cli` tests in the workflow when we run for a PR coming from a fork. I'll do that later (work is calling) unless you can do that directky in your PR?

**Comment by rathpc** [comment]
Hey @dcoraboeuf I am bringing this back to life with a small change that skips the ontrack-cli steps if running on a fork

**Comment by rathpc** [comment]
@dcoraboeuf Happy new year! just giving this a bump to make sure it doesn't get lost, thanks!

**Comment by dcoraboeuf** [comment]
Happy new year to you as well @rathpc ! I'm having a look at it right now, sorry for the big delays :(

**Comment by rathpc** [comment]
@dcoraboeuf thank you! Can you trigger a release so that new tags are available? I know you had an issue doing this the first time for the other action so I just wanted to call that out in case there is something you have to change for this one to fix that here as well.

**Comment by dcoraboeuf** [comment]
Done. Moved v1, created v1.1 and v1.10.

I seriously need to revisit the release process of these actions!

**Comment by rathpc** [comment]
> Done. Moved v1, created v1.1 and v1.10.
> 
> I seriously need to revisit the release process of these actions!

It should be v2, v2.0 and v2.0.0, not v1 to align with the tags in https://github.com/nemerosa/ontrack-github-actions-cli-setup

**Comment by dcoraboeuf** [comment]
Done as well :)

**Pull request merged**
